# Generated by Django 4.0.1 on 2023-06-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_activated',
        ),
    ]
